# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charpicture', '0003_auto_20170116_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesimplemodel',
            name='file_field',
            field=models.FileField(upload_to='upload'),
        ),
    ]
